version: '3'
services:
  web:
    build: 
      context: /var/lib/jenkins/workspace/Ansible_Project_Jobs/Docker_Compose_Demo
      dockerfile: /var/lib/jenkins/workspace/Ansible_Project_Jobs/Docker_Compose_Demo/Python-app/Dockerfile
    image: mypythonapp
    ports:
      - "5000:5000"
  redis:
    image: "redis:alpine"
  web:
    
