version: "3.4"
services:
  web:
    build: 
      context: .
      dockerfile: /Python-app/Dockerfile
    image: martin1051/pythonapp
    ports:
      - "5000:5000"
  redis:
    image: "redis:alpine"
    
