version: "3.4"
services:
  web:
    build: 
      context: .
      dockerfile: /Python-app/Dockerfile
    image: mypythonapp
    ports:
      - "5000:5000"
  redis:
    image: "redis:alpine"
  web:
    
