version: '3'
services:
  web:
    build: 
      context: ./Python-app
      dockerfile: Dockerfile
    image: mypythonapp
    ports:
      - "5000:5000"
  redis:
    image: "redis:alpine"
  web:
    
