From tomcat
Maintainer martinbrightin1@gmail.com
ADD /var/lib/jenkins/workspace/Ansible_Project_Jobs/Docker_Compose_Demo/Java-app/target/addressbook.war /usr/local/tomcat/webapps
CMD "catalina.sh" "run"
EXPOSE 8080
